#eureka:
#  application:
#    name: eureka-client
#  client:
#    port: 0
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#  instance:
#    preferIpAddress: true
#    lease-renewal-interval-in-seconds: 30
#    enabled: true
#    app name: eureka-client
#
spring:
  application:
    name: eureka-client
server:
  port: 8762
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      eureka-service-url-poll-interval-seconds: 35
  instance:
    preferIpAddress: true
#    lease-renewal-interval-in-seconds: 30
